# for MAPF benchmark
solver_name: "naive-lacam"
solver_options:
  - "--no-all"
num_min_agents: 50
num_max_agents: 100
num_interval_agents: 50
time_limit_sec: 5
seeds: 1  # the number of iterations
scen: scen-random
maps:
  # - Berlin_1_256
  # - Boston_0_256
  # - brc202d
  # - Paris_1_256
  # - den312d
  # - den520d
  # - empty-16-16
  # - empty-32-32
  # - empty-48-48
  # - empty-8-8
  # - ht_chantry
  # - ht_mansion_n
  # - lak303d
  # - lt_gallowstemplar_n
  # - maze-128-128-1
  # - maze-128-128-10
  # - maze-128-128-2
  # - maze-32-32-2
  # - maze-32-32-4
  # - orz900d
  # - ost003d
  # - random-32-32-10
  - random-32-32-20
  # - random-64-64-10
  # - random-64-64-20
  # - room-32-32-4
  # - room-64-64-16
  # - room-64-64-8
  # - w_woundedcoast
  # - warehouse-10-20-10-2-1
  # - warehouse-10-20-10-2-2
  # - warehouse-20-40-10-2-1
  # - warehouse-20-40-10-2-2
